<style type="text/css">
    .js #fouc {display: none;}
</style>
<script type="text/javascript">
      document.documentElement.className = 'js';
    console.log("Adding .js class to html element");
</script>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, height=device-height, initial-scale=1.0" />
<link rel="icon" type="image/png" href="images/icons/favicon-16x16.png" sizes="16x16" />
<link rel="icon" type="image/png" href="images/icons/favicon-32x32.png" sizes="32x32" />
<link rel="icon" type="image/x-icon" href="images/icons/favicon.ico" />
<link rel="shortcut icon" type="image/x-icon" href="images/icons/favicon.ico" />
<link rel="stylesheet" href="stylesheets/css-reset-min.css" type="text/css" />

<link rel="stylesheet/less" type="text/css" href="/stylesheets/style.less" />
<script src="//cdnjs.cloudflare.com/ajax/libs/less.js/2.5.0/less.min.js"></script>

<!-- <link rel="stylesheet" href="stylesheets/style.css" type="text/css" /> -->
<link rel="stylesheet" href="stylesheets/jquery.fancybox.css" type="text/css" media="screen" />

<link href='https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,200,300,300italic,400italic,200italic,600,600italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>

<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
<script type="application/ld+json">
	{
	  "@context" : "http://schema.org",
	  "@type" : "LocalBusiness",
	  "name" : "Twomey Carpentry",
	  "image" : "https://twomeycarpentry.com/images/home-banner.jpg",
	  "telephone" : "07923227280"
	}
</script>

<!-- Open Graph data -->
<meta property="og:title" content="Twomey Carpentry" />
<meta property="og:type" content="article" />
<meta property="og:url" content="https://www.twomeycarpentry.com/" />
<meta property="og:image" content="https://twomeycarpentry.com/images/home-banner.jpg" />
<meta property="og:image:width" content="1200" />
<meta property="og:image:height" content="590" />
<meta property="og:description" content="Bexhill Carpentry Services" />
<meta property="og:site_name" content="Twomey Carpentry" />