<!DOCTYPE html>

<head>
	<?php include("head.php"); ?>
    <title>Twomey Carpentry - Homepage</title>
    <meta name="robots" content="noindex,nofollow">

    <!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
    <script type="application/ld+json">
    {
      "@context" : "http://schema.org",
      "@type" : "LocalBusiness",
      "name" : "Twomey Carpentry",
      "image" : "https://twomeycarpentry.com/images/home-banner.jpg"
    }
    </script>

    <!-- Open Graph data -->
    <meta property="og:title" content="Twomey Carpentry" />
    <meta property="og:type" content="article" />
    <meta property="og:url" content="https://www.twomeycarpentry.com/" />
    <meta property="og:image" content="https://twomeycarpentry.com/images/home-banner.jpg" />
    <meta property="og:image" content="https://twomeycarpentry.com/images/about-banner.jpg" />
    <meta property="og:image" content="https://twomeycarpentry.com/images/contact-banner.jpg" />
    <meta property="og:image" content="https://twomeycarpentry.com/images/projects-banner.jpg" />
    <meta property="og:description" content="Bexhill Carpentry Services" />
    <meta property="og:site_name" content="Twomey Carpentry" />
</head>

<body>
	<div id="fouc">
        <div class="site-wrap">
			<?php include("header.php"); ?>

            <div class="page-content index">

                <div class="home-banner">
                    <img src="images/home-banner.jpg"/>
                </div>

                <div class="text">
                    <div class="content">
                        <h1>Twomey Carpentry</h1>
                        <p>We make your home beautiful again.</p>
                        <p>By combining our design skill and construction expertise, we guarantee you will be delighted with the finished result.</p>
                        <p>Give your home the makeover it deserves.</p>
                        <a href="about" class="button">Find out more about us</a>
                    </div>
                </div>

                <div class="image bathroom">
                </div>

                <div class="text">
                    <div class="content">
                        <h2>What We Do</h2>
                        <p>Our expert team can help with a wide range of tasks. From something as simple as a fresh lick of paint, to a complete home renovation involving demolishing and repositioning walls.</p>
                        <p>No job is too big or too small. </p>
                        <a href="contact" class="button">See what we can do for you</a>
                    </div>
                </div>

                <div class="image livingroom">
                </div>

                <div class="text">
                    <div class="content">
                        <h2>Why We Do It</h2>
                        <p>We love what we do. Every bit of our enthusiasm gets poured into every project, and the finished article reflects that. We take great satisfaction in delighting our clients, and giving them something to cherish for years.</p>
                        <a href="projects" class="button">View our previous work</a>
                    </div>
                </div>

            </div>

            <?php include("footer.php"); ?>
		</div>
	</div>

    <?php include("javascript-files.php"); ?>
    
</body>
